### ISSUE TITLE
Lua Error (Classic, Russian client, Att v. 0.4.3)

### ISSUE THREAD

**Issue by Alfrina** [DFortun81/ATT-Classic#100]
Date: 2021-01-06 09:58:29
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\ATT-Classic\ATT-Classic.lua line 1827:
   attempt to index local 'b' (a nil value)
Debug:
   ATT-Classic\ATT-Classic.lua:1827:
      ATT-Classic\ATT-Classic.lua:1825
   [C]: sort()
   ATT-Classic\ATT-Classic.lua:1825:
      ATT-Classic\ATT-Classic.lua:1395
   ATT-Classic\ATT-Classic.lua:2616:
      ATT-Classic\ATT-Classic.lua:2615
   ATT-Classic\ATT-Classic.lua:2712:
      ATT-Classic\ATT-Classic.lua:2618
   [C]: ?
   ...AddOns\Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:498: OnTooltipSetItem()
   Enchantrix\EnxMain.lua:232:
      Enchantrix\EnxMain.lua:228
   [C]: ?
   [C]: ?
   [C]: ?
   ...AddOns\Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:424:
      ...AddOns\Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:418
   [C]: SetBagItem()
   ..\FrameXML\ContainerFrame.lua:1327: ContainerFrameItemButton_OnEnter()
   Inventorian\Item.lua:294:
      Inventorian\Item.lua:279
Locals:
a = <table> {
 group = <table> {
 }
 right = "1x"
 prefix = "  "
}
b = nil
(*temporary) = "Великая таинственная субстанция"
(*temporary) = nil
(*temporary) = "attempt to index local 'b' (a nil value)"

**Comment by DFortun81** [comment]
This appears to have been fixed.
