### ISSUE TITLE
Missing

### ISSUE THREAD

**Issue by Chanizu** [DFortun81/ATT-Classic#101]
**Children's Week**
- [x] 171 - Missing https://classic.wowhead.com/quest=171/a-warden-of-the-alliance

- [x] 558 - Missing https://classic.wowhead.com/quest=558/jainas-autograph

- [x] 1468 - Missing https://classic.wowhead.com/quest=1468/childrens-week

- [x]  1479 - Missing https://classic.wowhead.com/quest=1479/the-bough-of-the-eternals

- [x] 1558 - Missing https://classic.wowhead.com/quest=1558/the-stonewrought-dam

- [x] 1687 - Missing https://classic.wowhead.com/quest=1687/spooky-lighthouse

- [x] 4822 -  Missing https://classic.wowhead.com/quest=4822/you-scream-i-scream

**Love is in the air**

- [x] 8903 - Missing https://classic.wowhead.com/quest=8903/dangerous-love

- [x] 9024 - Missing https://classic.wowhead.com/quest=9024/aristans-hunch

- [x] 9025 - Missing https://classic.wowhead.com/quest=9025/morgans-discovery

- [x] 9026 - Missing https://classic.wowhead.com/quest=9026/tracing-the-source

- [x] 9027 - Missing https://classic.wowhead.com/quest=9027/tracing-the-source

- [x] 9028 - Missing https://classic.wowhead.com/quest=9028/the-source-revealed

- [x] 9029 - Missing https://classic.wowhead.com/quest=9029/a-bubbling-cauldron

**Comment by DFortun81** [comment]
This appears to have been completed long ago.
