### ISSUE TITLE
Scourge Invasion Quests are not marked as collected

### ISSUE THREAD

**Issue by ceferrari** [DFortun81/ATT-Classic#102]
I did all Scourge Invasion quests while the event was still running. 

My ATT Classic did mark them all as done correctly, but recently Ive noticed its 12/20.

Some quests that were previously marked as done, are now unmarked.

What happened?

**Comment by Chanizu** [comment]
They were flagged as yearly quests by blizzard so their progress have been reset.
Github version reflects this.
