### ISSUE TITLE
Error When Mousing Over Items in Bag and Bank

### ISSUE THREAD

**Issue by Comicus** [DFortun81/ATT-Classic#104]
I get the following error when I mouse over items in my bag or bank...

20x ATT-Classic\ATT-Classic-0.4.6.lua:3948: bad argument DFortun81/AllTheThings#1 to 'ipairs' (table expected, got nil)
[C]: in function `ipairs'
ATT-Classic\ATT-Classic-0.4.6.lua:3948: in function <ATT-Classic\ATT-Classic.lua:3901>
ATT-Classic\ATT-Classic-0.4.6.lua:5021: in function `ItemTypeFilter'
ATT-Classic\ATT-Classic-0.4.6.lua:5010: in function `GroupFilter'
ATT-Classic\ATT-Classic-0.4.6.lua:5080: in function `RecursiveGroupRequirementsFilter'
ATT-Classic\ATT-Classic-0.4.6.lua:1343: in function <ATT-Classic\ATT-Classic.lua:1341>
ATT-Classic\ATT-Classic-0.4.6.lua:1783: in function <ATT-Classic\ATT-Classic.lua:1395>
ATT-Classic\ATT-Classic-0.4.6.lua:2616: in function <ATT-Classic\ATT-Classic.lua:2615>
ATT-Classic\ATT-Classic-0.4.6.lua:2712: in function <ATT-Classic\ATT-Classic.lua:2618>
[C]: ?
[C]: ?
[C]: ?
...
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: in function `SetBagItem'
FrameXML\ContainerFrame.lua:1327: in function `ContainerFrameItemButton_OnEnter'
...faceBagnon\common\Wildpants\classes\item.lua:369: in function `ShowTooltip'
...faceBagnon\common\Wildpants\classes\item.lua:340: in function `UpdateTooltip'
...faceBagnon\common\Wildpants\classes\item.lua:180: in function <...faceBagnon\common\Wildpants\classes\item.lua:179>

Locals:
(*temporary) = nil
(*temporary) = "itemID"
(*temporary) = 5525
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1

**Comment by DFortun81** [comment]
I have a fix for this on Git.

**Comment by Comicus** [comment]
No errors, Thank you very much
