### ISSUE TITLE
Missing Quest "The Public Servant"

### ISSUE THREAD

**Issue by Zephryl87** [DFortun81/ATT-Classic#109]
The Quest "The Public Servant" seems to not be in the database of WoW Classic ATT. There were a couple more things, that I noticed and I will post them here, if I find them again

**Comment by Molkree** [comment]
@Zephryl87, I can see this quest in the database, not sure why you can't see it.
https://github.com/DFortun81/ATT-Classic/blob/166f46f064a2f05a8346d596299107d24fe9d1a5/.contrib/.db/02%20-%20Outdoor%20Zones/02%20Eastern%20Kingdoms/Dun%20Morogh/Quests.lua#L631-L637

It is marked as a yearly quest, meaning that it is repeatable, which might be why you don't see it.

Please, confirm that it is in fact there and close this issue then.

**Comment by DFortun81** [comment]
The quest isn't missing, it's marked Yearly. This means it can be repeated. Repeatable quests do not appear as something to collect forever in ATT-Classic, you'd need to turn on "Show Incomplete Things" to track it.
