### ISSUE TITLE
Quests still showing up incomplete.

### ISSUE THREAD

**Issue by badbranni** [DFortun81/ATT-Classic#11]
Hi,
1) https://classic.wowhead.com/quest=431/candles-of-beckoning
2) https://classic.wowhead.com/quest=410/the-dormant-shade
those are the 2 quests that show as incomplete, even though they are a part of a quest chain, those quests are repeatable. maybe that's why they showing up as incomplete.
Anyway, when you complete the whole chain, they become unobtainable to repeat.. but they still showing up as incomplete in the addon after /reload.

3) https://classic.wowhead.com/quest=5847/welcome
Another quest that showing up incomplete even though it is no longer obtainable

4) https://classic.wowhead.com/quest=787/the-new-horde
This one should be marked as completed or inactive when you complete the alternative https://classic.wowhead.com/quest=4641/your-place-in-the-world so that the main quest becomes unobtainable.

5) https://classic.wowhead.com/quest=792/vile-familiars
not available quest for undead... for whatever reason but its still showing incomplete
edit: apparently this is the alternative quest for warlocks, the main one https://classic.wowhead.com/quest=1485/vile-familiars should be marked completed too

6) https://classic.wowhead.com/quest=785/a-strategic-alliance
i think this quest is just in the game files, cant get it anywhere

Plz fix. thank you.

**Comment by PeterMorganGH** [comment]
The fix for these quests should be coming in the next release of the addon - whenever that is.
