### ISSUE TITLE
Missing pet skill Nature Resistance

### ISSUE THREAD

**Issue by Jokaleth** [DFortun81/ATT-Classic#119]
![image](https://user-images.githubusercontent.com/87456827/132263591-c73a0694-a581-428c-aa3c-da1e34ddec34.png)

**Comment by DFortun81** [comment]
That appears to be the night elf racial. https://www.wowhead.com/spell=20583/nature-resistance

However I think I fixed this bug a long time ago. Please let me know if it's still an issue in Classic Era.
