### ISSUE TITLE
Horde alligned quests showing up in quests as Alliance

### ISSUE THREAD

**Issue by ssateneth** [DFortun81/ATT-Classic#15]
There are numerous quests that are horde only that are showing up for alliance due to the quest giver or turnin being horde aligned. Here are a list of ID's for each zone I've seen that are causing issues.

Un'goro: 4148, 4148, 4147
Azshara: 3564, 3542, 3561, 3518, 3562, 3565, 3517. Also 3381 and 3382 are not collectible (repeatable)
Tanaris: 841, 4509, 243, 379, 654
Barrens: 3514, 886

**Comment by TKTalonzor** [comment]
Updated on git
