### ISSUE TITLE
Repeatable quests showing in ATT

### ISSUE THREAD

**Issue by ssateneth** [DFortun81/ATT-Classic#16]
There are a number of repeatable quests that show up in ATT. As I come across them, I will list them in the issue ticker. They should either be removed or put in it's own "repeatable quest" category so they can be filtered out since they will never be shown as in a collected state. Quest ID's are as follows.

7801, 3803, 3792

**Comment by ssateneth** [comment]
Also ID's 2602, 3502, 2582

**Comment by ssateneth** [comment]
Add on 4803, 4807, 4802, 4804, 4806, 4801, 4805 in winterspring

**Comment by TKTalonzor** [comment]
> There are a number of repeatable quests that show up in ATT. As I come across them, I will list them in the issue ticker. They should either be removed or put in it's own "repeatable quest" category so they can be filtered out since they will never be shown as in a collected state. Quest ID's are as follows.
> 
> 7801, 3803, 3792

done

**Comment by ssateneth** [comment]
There are also a TON of quests in Felwood for applying the salves to the corrupted plants in Felwood. Some are marked as repeatable in Wowhead, but it's likely they all are and they just haven't gotten enough data from datamining to confirm they are repeatable or not.

Corrupted Night Dragon 4447, 4448, 4462, 4119
Corrupted Songflower 3363, 4401, 4465, 4464, 4116, 4118, 4114, 4113, 2523
Corrupted Whipper Root 4461, 4446, 4444, 4443, 4445, 4117
Corrupted Windblossom 4222, 4115, 4343, 4221, 4467, 4466, 1514, 998, 996

Associated cenarion salve quests, also repeatable 4110, 4105, 4108, 4103, 4104, 4109, 4106, 4111, 4112, 4107

**Comment by ssateneth** [comment]
In feralas...

ID's 7725, 7735, 7726, 4041, 3567

**Comment by ssateneth** [comment]
Thousand needles...

ID's 1192, 1191

**Comment by ssateneth** [comment]
Un'Goro...

5150. The crystal quests are correctly marked as repeatable and not counting against completion.

**Comment by ssateneth** [comment]
Badlands...

795 [Horde], 779 [Alliance] (These quests are repeatable and only temporarily available as part of the Tremors of the Earth (717 Alliance) and Broken Alliances (793 Horde) quests)

**Comment by ssateneth** [comment]
Blasted lands...

3502, 2586, 2584, 2604

**Comment by ssateneth** [comment]
Duskwood...

254 (Only available when on quest 253)

**Comment by ssateneth** [comment]
Stranglethorn Vale...

619 (Temporary repeatable quest while on 8554 and/or 618, need confirmation. "Facing Negolash" quest for Smotts' Compass)
1127 Is allegedly repeatable but I have not been able to pick up the quest.
349 is repeatable for the purpose of quest ID 348 to summon Mokk for his heart drop.

**Comment by ssateneth** [comment]
Hinterlands...

2881

**Comment by ssateneth** [comment]
Ironforge...

3483

**Comment by javierhimura** [comment]
This will be fixed by migrating to ATT-Classic the changes of my 3 last Merge Request for ATT-Retail that improve the filter of repeatable quest and fix it for those kinds of old school repeatable that exits in Classic. Those pull request also contains changes for yearly quest, unlike daily or weekly quests that are available in Classic for seasonal events. Of course, ignore any change for non-Classic quests

https://github.com/DFortun81/AllTheThings/pull/360
https://github.com/DFortun81/AllTheThings/pull/361
https://github.com/DFortun81/AllTheThings/pull/362

**Comment by PeterMorganGH** [comment]
> 
> 
> In feralas...
> 
> ID's 7725, 7735, 7726, 4041, 3567

All of these are marked as repeatable.

**Comment by PeterMorganGH** [comment]
- Thousand needles
  - [ ] 1192
  - [ ] 1191


- Un'Goro
  - [ ] 5150: The crystal quests are correctly marked as repeatable and not counting against completion.


- Badlands
  - [ ] 795 (Horde)
  - [ ] 779 (Alliance)
  - These quests are repeatable and only temporarily available as part of the Tremors of the Earth (717 Alliance) and Broken Alliances (793 Horde) quests)

- Blasted lands
  - [ ] 3502
  - [ ] 2586
  - [ ] 2584
  - [ ] 2604

- Duskwood
  - [ ] 254 (Only available when on quest 253)

- Stranglethorn Vale...
  - [ ] 619 (Temporary repeatable quest while on 8554 and/or 618, need confirmation. "Facing Negolash" quest for Smotts' Compass)
  - [ ] 1127 Is allegedly repeatable but I have not been able to pick up the quest.
  - [ ] 349 is repeatable for the purpose of quest ID 348 to summon Mokk for his heart drop.

- Hinterlands
  - [ ] 2881

- Ironforge
  - [ ] 3483
  - [ ] 7342

**Comment by PeterMorganGH** [comment]
The fix for this has been implemented and will be in the next release.
