### ISSUE TITLE
Need a "repeatable quest" filter

### ISSUE THREAD

**Issue by ssateneth** [DFortun81/ATT-Classic#17]
While repeatable quests can be turned in, they will never be marked as "complete" by the the IsQuestFlaggedCompleted() API, so there is no concrete way to designate a repeatable quest as complete. I suggest to add a filter catefory to filter out repeatable quests, for those people that are triggered by repeatable quests preventing them from 100%-ing an area (myself included)

**Comment by DFortun81** [comment]
We already do. It's turned on by default. If you find a repeatable quest that isn't marked as Repeatable, please report the quest.
