### ISSUE TITLE
How do we handle exclusive quests?

### ISSUE THREAD

**Issue by ssateneth** [DFortun81/ATT-Classic#18]
Some quests are exclusive from each other. How are those handled? For example, "Escape Through Stealth" and "Escape Through Force" in Darkshore (ID 995 and 994) are exclusive; you can only do one or the other. I'll add more quests as I find them.

**Comment by ssateneth** [comment]
I think some breadcrumbs might belong here too, but if you do the sequence of quests correctly, you can at least get some of them done. Either case, ID's 1301 and 1282 are impossible for me to pick up,

1301 seems to be a breadcrumb of 1302. Not sure about 1282 to be honest. It may be locked out from a quest either accepted or completed from NPC 4944 "Captain Garran Vimes"

**Comment by ssateneth** [comment]
Another breadcrumb, 7494 though I can't seem to locate what it's a breadcrumb to yet.

**Comment by ssateneth** [comment]
Another breadcrumb in Dun Morogh, ID 415. Completable, but requires 315 to be completed first. It is a breadcrumb to quest 413. If 413 is completed, 415 will never be available again.

**Comment by ssateneth** [comment]
In Duskwood... Quests 526 and 624 MIGHT be exclusive. Need confirmation. Also, quest 402 is a breadcrumb to SOMETHING, but only if the "Stitches" NPC is attacking Duskwood (At least, that's the theory). Need testing to confirm.

**Comment by JonasSchlatter** [comment]
["altQuests"] is the tag you're looking for. (:

**Comment by TKTalonzor** [comment]
> Some quests are exclusive from each other. How are those handled? For example, "Escape Through Stealth" and "Escape Through Force" in Darkshore (ID 995 and 994) are exclusive; you can only do one or the other. I'll add more quests as I find them.

We will mark them as "alternative" quests, when you complete one, it will mark as completed the other one.

**Comment by ssateneth** [comment]
Quest 1301 is a breadcrumb to 1302. I have completed 1302 and 1301 is not available to pick up anymore.

**Comment by ssateneth** [comment]
7494 is complete on my end. Using build 05a2cd0bb488dbe2e4753691151af2a6e1910087 (latest as of writing this response)

https://i.imgur.com/eqDZ4Dc.png

**Comment by PeterMorganGH** [comment]
The fix for this has been implemented and will be in the next release.
