### ISSUE TITLE
Deprecated or unavailable quests

### ISSUE THREAD

**Issue by ssateneth** [DFortun81/ATT-Classic#20]
Some quests SEEM to be unavailable, either because they were never enabled, or the quest giver doesn't exist, or were deprecated sometime during the original patch cycles. These may need more research to reach a decision on.

ID 1272 "Finding Reethe <CHANGE INTO GOSSIP>"
ID 1283 "Fire at the Shady Rest <CHANGE TO GOSSIP>"
ID 1281 "Jim's Song <CHANGE TO GOSSIP>"
ID 9065 "The "Chow" Quest (123)aa"
ID 1 "The "Chow" Quest (123)aa"
ID 1263 "The Burning Inn <CHANGE TO GOSSIP>"
ID 1288 "Vimes's Report" (seems to have deprecated in later patches)

**Comment by ssateneth** [comment]
Badlands: Add on 708 possibly as deprecated (Starts from Item ID 4613 [Corroded Black Box] which dropped from NPC ID 2931 [Zaricotl], but the item reportedly no longer drops)

**Comment by ssateneth** [comment]
Loch Modan: 912, MAYBE. It has something to do with Itme ID 5131, and there is no other information available. Seems to only apply to rogues. No other information available.

**Comment by PeterMorganGH** [comment]
These have been marked as unobtainable.
