### ISSUE TITLE
Classic ATT Hunter Pet Spells

### ISSUE THREAD

**Issue by Sionnix** [DFortun81/ATT-Classic#32]
![image](https://user-images.githubusercontent.com/47155150/65840517-6f05ae00-e2d7-11e9-8c20-5f3b8f5c31c5.png)

ATT keeps tells me to report this so here it is.

**Comment by PeterMorganGH** [comment]
Pet skill Spell IDs have been added so this "report" text should no longer appear. There is still an issue with the functionality of pet skill tracking which has a new issue: #46.
