### ISSUE TITLE
Incomplete quests

### ISSUE THREAD

**Issue by badbranni** [DFortun81/ATT-Classic#33]
Hey there,
These are some quests that should be marked as complete

1) https://classic.wowhead.com/quest=758/thunderhorn-cleansing
Tauren only quest, showing as incomplete for undead race.
2) https://classic.wowhead.com/quest=792/vile-familiars
This quest cannot be obtained by undead warlock because they get a differnet one which is: https://classic.wowhead.com/quest=1485/vile-familiars
3) https://classic.wowhead.com/quest=431/candles-of-beckoning
https://classic.wowhead.com/quest=410/the-dormant-shade
2 repeatable quests while the chain https://classic.wowhead.com/quest=409/proving-allegiance
is active. When u complete the chain, those quests become unavailable to complete.
4) https://classic.wowhead.com/quest=787/the-new-horde
should be marked as complete after u do the alternative which is https://classic.wowhead.com/quest=4641/your-place-in-the-world

**Comment by PeterMorganGH** [comment]
>     1. https://classic.wowhead.com/quest=758/thunderhorn-cleansing
>        Tauren only quest, showing as incomplete for undead race.

This quest has been fixed in [this commit](https://github.com/DFortun81/ATT-Classic/commit/d89fd8e1237db595db78a4e0f5605bc2a8f1f0e9)

**Comment by PeterMorganGH** [comment]
The fix for these quests should be coming in the next release of the addon - whenever that is.
