### ISSUE TITLE
Missing SpellID for pet spells

### ISSUE THREAD

**Issue by Summersisle** [DFortun81/ATT-Classic#37]
When opening the Beast Training on Hunter ATT throws errors that it cannot find spell id's for all the beast spells

![image](https://user-images.githubusercontent.com/25886892/67164333-67618400-f32e-11e9-8406-6abc8cdbdc53.png)

**Comment by PeterMorganGH** [comment]
Pet skill Spell IDs have been added so this "report" text should no longer appear. There is still an issue with the functionality of pet skill tracking which has a new issue: #46.
