### ISSUE TITLE
Commit c0be613 broke TSM compatability

### ISSUE THREAD

**Issue by ssateneth** [DFortun81/ATT-Classic#38]
with commit c0be613bac4c41e0250282f7688fd9cfee8331d1 it broke TSM4 classic compatability. If you have ATT classic commit c0be613bac4c41e0250282f7688fd9cfee8331d1 or later loaded + any build of TSM4 running and you open a profession window (alchemy as an example) and the TSM4 modified profession window opens up, if you close the TSM4 modified window, it freezes WoW. If I revert the modified window to blizzard default one before closing it, it wont freeze. If I dont use ATT or use a commit before c0be613bac4c41e0250282f7688fd9cfee8331d1 then it also will not freeze wow client if I close TSM modified profession window.

**Comment by PeterMorganGH** [comment]
I can confirm the issue. WoW will freeze when using TSM's profession UI with ATT's profession list open. I had this happen with TSM version 4.8.20.

**Comment by PeterMorganGH** [comment]
@ssateneth I pushed a change that fixed this for me. Can you try it out and see if it works for you?

**Comment by ssateneth** [comment]
Using build 05a2cd0bb488dbe2e4753691151af2a6e1910087 and the issue seems fixed now. No more freezing for me with TSM modified profession windows and ATT loaded at the same time.

**Comment by PeterMorganGH** [comment]
The fix for this has been implemented and will be in the next release.
