### ISSUE TITLE
Jonespyre's Request breadcrumb

### ISSUE THREAD

**Issue by ssateneth** [DFortun81/ATT-Classic#47]
The "Jonespyre's Request" quests (id 3787 and 3788) are breadcrumbs to "The Mystery of Morrowgrain" (id 3791). I can't pick up either of the breadcrumbs since 3791 is flagged completed for me. It's quite possible 3787 and 3788 are exclusive too but need testing to confirm.

I have 3791 complete in ATT but 3788 is showing as something I need to do / incomplete

**Comment by PeterMorganGH** [comment]
@ssateneth 3787 wasn't even in the addon, so I added it in. 3787 and 3788 are now linked as alt quests, so completing one should complete the other. I read some WoWHead comments about this quest chain and was sort of confused by it. I'm tempted not to mess with this any more until 1) I get to do the quest chain myself or 2) another contributor who has done the quest line takes a look at it.

**Comment by ssateneth** [comment]
Seems unresolved still. 3787 and 3788 cannot be picked up by me. I'm currently on build 05a2cd0bb488dbe2e4753691151af2a6e1910087  See pictures.

https://i.imgur.com/pp9w8s9.png
https://i.imgur.com/mdPqRYo.png

same result with orange X next to both honespyre's request with show collected thigns and show completed groups NOT ticked.

**Comment by PeterMorganGH** [comment]
ssateneth has confirmed that this issue has been resolved.
