### ISSUE TITLE
"They Call Him Smiling Jim" exclusive breadcrumb

### ISSUE THREAD

**Issue by ssateneth** [DFortun81/ATT-Classic#48]
"They Call Him Smiling Jim" (id 1282) is exclusive from "James Hyal" (id 1302, and also has a crumb of the same name, id 1301). Once one is completed, the other is unavailable. They are breadcrumbs that lead to Captain Garran Vimes (npc 4844) and his various quests, but I don't know if picking up and/or completing vime's quests disables the 2 breadcrumbs listed

ATT is showing 1282 available even though I have 1302 complete.

**Comment by PeterMorganGH** [comment]
@ssateneth 1282 is currently linked to 1301, but I think it should be linked to 1302. Do you have 1301 completed?

**Comment by ssateneth** [comment]
1302 is completed, 1301 is NOT completed.

**Comment by PeterMorganGH** [comment]
@ssateneth 1301 was already marked as a breadcrumb. I changed it so that 1302 and 1282 are linked as alt quests. Does that help?

**Comment by ssateneth** [comment]
Seems resolved on my end, using build 05a2cd0bb488dbe2e4753691151af2a6e1910087 1282 is circle checkmark with 1302 regular checkmark. I'm assuming a blue circle checkmark means the quest is superceded by a different quest that is alerady complete (aka breadcrumb or similar)

**Comment by PeterMorganGH** [comment]
The fix for this has been implemented and will be in the next release.
