### ISSUE TITLE
"Pristine Yeti Hide" is repeatable, not collectible

### ISSUE THREAD

**Issue by ssateneth** [DFortun81/ATT-Classic#50]
"Pristine Yeti Hide" (id 7735) starts from an item only looted by alliance characters, but is repeatable and not permanently collectible (kind of like the "healthy dragon scale" quest starter that drops from whelps in scholomance)

Quest 7735 is showing in my ATT as uncollected.

**Comment by PeterMorganGH** [comment]
The fix for this has been implemented and will be in the next release.
