### ISSUE TITLE
"Taking Back Silithus" quests and follow-ups are inactive in current phase

### ISSUE THREAD

**Issue by ssateneth** [DFortun81/ATT-Classic#53]
the quest "Taking Back Silithus" (id 8275 and 8276) and the followup quests 8280 and 8281 are not available in phase 1 of classic, so they proabbly show not yet be showing in the ATT list of collectible quests and instead enabled when the appropriate phase is enabled on the servers.

**Comment by PeterMorganGH** [comment]
8280 and 8281 were already marked as unobtainable. I marked 8275 and 8276 as unobtainable. This change will be in the next release.
