### ISSUE TITLE
A couple "Missing in ATT" quests

### ISSUE THREAD

**Issue by ssateneth** [DFortun81/ATT-Classic#57]
Quests 3366, 6842, and 7169 is showing up as completed quest but missing in ATT on login as of 05a2cd0bb488dbe2e4753691151af2a6e1910087 on a level 60 alliance human warrior

https://i.imgur.com/5IxzSa7.png

3366 is easy enough, just a wailing caverns quest started from an item that drops off last boss. The other two are a headscratcher... will check ATT debug history.

**Comment by PeterMorganGH** [comment]
3366 has been confirmed fixed.

**Comment by PeterMorganGH** [comment]
In commit https://github.com/DFortun81/ATT-Classic/commit/d7bd9240dca1d67258d075a2aa848ff0bf569769 I added 6842 and 7069 to [NYI.lua](https://github.com/DFortun81/ATT-Classic/blob/master/.contrib/Parser/DATAS/07%20-%20NYI/NYI.lua) in an attempt to stop them from reporting as missing.

**Comment by PeterMorganGH** [comment]
We still don't know what triggers 6842 and 7069 to complete, but at least they have been confirmed to no longer report that they are missing.
