### ISSUE TITLE
Quest Report

### ISSUE THREAD

**Issue by federicobattistin** [DFortun81/ATT-Classic#61]
I've gathered up a few quests I've encountered so far that are marked incorrectly. 

I'm on the horde side, so some quests are marked as "Alliance Only" because they are Alliance-only quests and should not be shown to horde characters.

I've left out a few quests, since I've seen they've already been reported in other issues.

Format: [Quest ID] Quest Name (Reason)

* KALIMDOR
  * ORGRIMMAR
    * [7341] A Fair Trade (**Repeatable**)
    * [8917] An Earnest Proposition + The Whole Dungeon 2 Chain (**Available in Later Phase**)
    * [7783] The Lord of Blackrock (**Available in Later Phase**)
  * THUNDER BLUFF
    * [769] Kodo Hide Bag (**Requires Leatherworking 10**)
    * [3804] Morrowgrain to Thunder Bluff (**Repeatable**)
  * AZSHARA
    * [3503] Meeting with the Master (**Repeatable**)
    * [8729] The Wrath of Neptulon (**Available in Later Phase**)
  * DESOLACE
    * [1466] Reagents for Reclaimers Inc. (**Alliance Only**)
    * [1467] Reagents for Reclaimers Inc. (**Alliance Only**)
    * [5421] Fish in a Bucket (**Repeatable**)
  * FERALAS
    * [7738] Perfect Yeti Hide (**Repeatable**)
  * TANARIS
    * [841] Another Power Source (**Repeatable**)
    * [4508] Calm Before the Storm (**Alliance Only**)
  * THOUSAND NEEDLES
    * [1099] Goblins Win! (**Deprecated**)
    * [1174] Gnomes Win!	(**Deprecated**)
    * [1191] Zamek’s Distraction (**Quest Progress Step: [1190]**)
  * WINTERSPRING
    * [5252] Remorseful Highborne (**Alliance Only**)
    * [5253] The Crystal of Zin-Malor (**Alliance Only**)
    * [6606] A Little Luck (**Deprecated**)

* EASTERN KINGDOMS
  * UNDERCITY
    * [4561] Testing for Impurities – Un’Goro Crater (**Quest Progress Step: [4294]**)
    * [4661] Testing for Corruption – Felwood	(**Quest Progress Step: [4293]**)
    * [5658] Touch of Weakness (**Priest Only**)
  * ARATHI HIGHLANDS
    * [696] Attack on The Tower (**Alliance Only**)
    * [697] Malin’s Request (**Alliance Only**)
  * BADLANDS
    * [706] Fiery Blaze Enchantment	(**Alliance Only**)
    * [717] Tremors of the Earth (**Alliance Only**)
    * [732] Tremors of the Earth (**Alliance Only**)
    * [2203] Badlands Reagent Run II (**Requires Alchemy 210**)
  * DUSKWOOD
    * [526] Lightforge Ingots (**Alliance Only**)
    * [1395] Supplies for Nethergarde (**Alliance Only**)
  * STRANGLETHORN VALE
    * [206] Mai’Zoth (**Alliance Only**)
    * [593] Filling the Soul Gem (**Quest Progress Step: [592]**)
  * SWAMP OF SORROWS
    * [1396] Encroaching Wildlife (**Alliance Only**)
    * [1398] Driftwood (**Alliance Only**)
    * [1421] The Lost Caravan (**Alliance Only**)
    * [1425] Deliver the Shipment (**Alliance Only**)

* DUNGEONS & RAIDS
  * SCARLET MONASTERY
    * [1049] Compendium of the Fallen (**Available to Non-Undeads Only**)
  * THE DEADMINES
    * [373] The Unsent Letter (**Alliance Only**)

I still haven't check a few zones thoroughly (Eastern Plaguelands, Burning Steppes, Western Plaguelands) and a few 58+ dungeons/raids.

Keep up the amazing work, can't wait for the next release!

**Comment by PeterMorganGH** [comment]
* KALIMDOR
  * ORGRIMMAR
    * [ ] [7341] A Fair Trade (**Repeatable**)
    * [ ] [8917] An Earnest Proposition + The Whole Dungeon 2 Chain (**Available in Later Phase**)
    * [ ] [7783] The Lord of Blackrock (**Available in Later Phase**)
  * THUNDER BLUFF

    * [ ] [769] Kodo Hide Bag (**Requires Leatherworking 10**)
    * [ ] [3804] Morrowgrain to Thunder Bluff (**Repeatable**)
  * AZSHARA
    * [ ] [3503] Meeting with the Master (**Repeatable**)
    * [ ] [8729] The Wrath of Neptulon (**Available in Later Phase**)
  * DESOLACE
    * [ ] [1466] Reagents for Reclaimers Inc. (**Alliance Only**)
    * [ ] [1467] Reagents for Reclaimers Inc. (**Alliance Only**)
    * [ ] [5421] Fish in a Bucket (**Repeatable**)
  * FERALAS
    * [ ] [7738] Perfect Yeti Hide (**Repeatable**)
  * TANARIS
    * [ ] [841] Another Power Source (**Repeatable**)
    * [ ] [4508] Calm Before the Storm (**Alliance Only**)
  * THOUSAND NEEDLES
    * [ ] [1099] Goblins Win! (**Deprecated**)
    * [ ] [1174] Gnomes Win!	(**Deprecated**)
    * [ ] [1191] Zamek’s Distraction (**Quest Progress Step: [1190]**)
  * WINTERSPRING
    * [ ] [5252] Remorseful Highborne (**Alliance Only**)
    * [ ] [5253] The Crystal of Zin-Malor (**Alliance Only**)
    * [ ] [6606] A Little Luck (**Deprecated**)

* EASTERN KINGDOMS
  
  * UNDERCITY
    * [ ] [4561] Testing for Impurities – Un’Goro Crater (**Quest Progress Step: [4294]**)
    * [ ] [4661] Testing for Corruption – Felwood	(**Quest Progress Step: [4293]**)
    * [ ] [5658] Touch of Weakness (**Priest Only**)
  * ARATHI HIGHLANDS
    
    * [ ] [696] Attack on The Tower (**Alliance Only**)
    * [ ] [697] Malin’s Request (**Alliance Only**)
  * BADLANDS
    
    * [ ] [706] Fiery Blaze Enchantment	(**Alliance Only**)
    * [ ] [717] Tremors of the Earth (**Alliance Only**)
    * [ ] [732] Tremors of the Earth (**Alliance Only**)
    * [ ] [2203] Badlands Reagent Run II (**Requires Alchemy 210**)
  * DUSKWOOD
    
    * [ ] [526] Lightforge Ingots (**Alliance Only**)
    * [ ] [1395] Supplies for Nethergarde (**Alliance Only**)
  * STRANGLETHORN VALE
    
    * [ ] [206] Mai’Zoth (**Alliance Only**)
    * [ ] [593] Filling the Soul Gem (**Quest Progress Step: [592]**)
  * SWAMP OF SORROWS
    
    * [ ] [1396] Encroaching Wildlife (**Alliance Only**)
    * [ ] [1398] Driftwood (**Alliance Only**)
    * [ ] [1421] The Lost Caravan (**Alliance Only**)
    * [ ] [1425] Deliver the Shipment (**Alliance Only**)
 
* DUNGEONS & RAIDS
  
  * SCARLET MONASTERY
    
    * [ ] [1049] Compendium of the Fallen (**Available to Non-Undeads Only**)
  * THE DEADMINES
    
    * [ ] [373] The Unsent Letter (**Alliance Only**)

**Comment by PeterMorganGH** [comment]
@federicobattistin Thank you for submitting this issue. I have made the necessary changes and they will be in the next release.
