### ISSUE TITLE
[Classic] Schematic: Lil' Smoky and Schematic: Pet Bombling

### ISSUE THREAD

**Issue by Sadane** [DFortun81/ATT-Classic#63]
Both Lil' Smoky and Schematic: Pet Bombling listed as drop from Gnomeregan but its only optainable by renewing your gnomish/goblin engineering membership.

**Comment by PeterMorganGH** [comment]
This issue should be fixed with this commit https://github.com/DFortun81/ATT-Classic/commit/66aa2ce86880320bde78d6519acc3581b0498f14.
