### ISSUE TITLE
Quests, not available to Horde in horde character list

### ISSUE THREAD

**Issue by Sadane** [DFortun81/ATT-Classic#64]
Here is list of quests i found so far
https://classic.wowhead.com/quest=1384/raid-on-the-kolkar
https://classic.wowhead.com/quest=4262/overmaster-pyron
https://classic.wowhead.com/quest=3823/extinguish-the-firegut
https://classic.wowhead.com/quest=4283/fifty-yep
https://classic.wowhead.com/quest=3825/ogre-head-on-a-stick-party
https://classic.wowhead.com/quest=3741/hilarys-necklace
https://classic.wowhead.com/quest=1579/gaffer-jacks
https://classic.wowhead.com/quest=1580/electropellers

**Comment by PeterMorganGH** [comment]
@Sadane Thank you for sharing the links. We'll take a look and make any necessary changes.

**Comment by TKTalonzor** [comment]
Done on git.

**Comment by federicobattistin** [comment]
Hilary's Necklace (ID 3741) should not be Alliance Only as it is in fact completable by horde characters.
