### ISSUE TITLE
A few Issues and Missing Quests

### ISSUE THREAD

**Issue by federicobattistin** [DFortun81/ATT-Classic#66]
Here are a few issues I've encountered in release 0.1.3, plus a few missing quests.

ISSUES
* KALIMDOR
  * ORGRIMMAR
    * [8978] Return to Mokvar (**Available in Phase 5**)
    * [8927-8938-8939-8940-8941-8942-8943-8944] Just Compensation (**Available in Phase 5**)
    * [8957-9016-9017-9018-9019-9020-9021-9022] Anthion’s Parting Words (**Available in Phase 5**)
    * [8998] Back to the Beginning (**Available in Phase 5**)
    * [9007-9008-9009-9010-9011-9012-9013-9014] Saving the Best for Last (**Available in Phase 5**)
    * [7784] The Lord of Blackrock (**Available in Phase 3**)
    * [7926] The Darkmoon Faire (**Available in Phase 3**)

* EASTERN KINGDOMS
  * SWAMP OF SORROWS
    * [1418] Neeka Bloodscar (**Breadcrumb, should be marked as completed if followup is completed**)
  * WESTERN PLAGUELANDS
    * [5059] Locked Away (**Repeatable**)

* DUNGEONS & RAIDS
  * MOLTEN CORE
    * [7785] Examine the Vessel (**Available in Phase 3**)
    * [7786] Thunderaan the Windseeker (**Available in Phase 3**)
    * [7787] Rise, Thunderfury! (**Available in Phase 3**)

MISSING QUESTS
 * UNDEAD ROGUE ONLY
    * 1885
    * 1886
    * 1898
    * 1899
    * 1978
    * 1998
    * 1999
    * 3096
 * ROGUE ONLY
    * 2378
    * 2379
    * 2381
    * 2382
    * 2458
    * 2460
    * 2478
    * 2479
    * 2480
 * ALTERAC VALLEY
    * 7241

**Comment by PeterMorganGH** [comment]
### ISSUES

- KALIMDOR

  - ORGRIMMAR

    - [ ] [8978] Return to Mokvar (**Available in Phase 5**)
    - [ ] [8927-8938-8939-8940-8941-8942-8943-8944] Just Compensation (**Available in Phase 5**)
    - [ ] [8957-9016-9017-9018-9019-9020-9021-9022] Anthion’s Parting Words (**Available in Phase 5**)
    - [ ] [8998] Back to the Beginning (**Available in Phase 5**)
    - [ ] [9007-9008-9009-9010-9011-9012-9013-9014] Saving the Best for Last (**Available in Phase 5**)
    - [ ] [7784] The Lord of Blackrock (**Available in Phase 3**)
    - [ ] [7926] The Darkmoon Faire (**Available in Phase 3**)

- EASTERN KINGDOMS

  - SWAMP OF SORROWS

    - [ ] [1418] Neeka Bloodscar (**Breadcrumb, should be marked as completed if followup is completed**)

  - WESTERN PLAGUELANDS

    - [x] [5059] Locked Away (**Repeatable**)

- DUNGEONS & RAIDS

  - MOLTEN CORE

    - [ ] [7785] Examine the Vessel (**Available in Phase 3**)
    - [ ] [7786] Thunderaan the Windseeker (**Available in Phase 3**)
    - [ ] [7787] Rise, Thunderfury! (**Available in Phase 3**)

### MISSING QUESTS

- UNDEAD ROGUE ONLY

  - [ ] 1885
  - [ ] 1886
  - [ ] 1898
  - [ ] 1899
  - [ ] 1978
  - [ ] 1998
  - [ ] 1999
  - [ ] 3096

- ROGUE ONLY

  - [ ] 2378
  - [ ] 2379
  - [ ] 2381
  - [ ] 2382
  - [ ] 2458
  - [ ] 2460
  - [ ] 2478
  - [ ] 2479
  - [ ] 2480

- ALTERAC VALLEY

  - [x] 7241

**Comment by PeterMorganGH** [comment]
@federicobattistin Thank you for creating this issue. The fixes for have been implemented and will be in the next release.
