### ISSUE TITLE
Mulgore quests marked as alliance obtainable even though they are Horde only

### ISSUE THREAD

**Issue by GodlFire** [DFortun81/ATT-Classic#68]
Mulgore Quests 'Poison Water' 'Thunderhorn Totem' 'Winterhoof Cleansing' are marked as obtainable by alliance even though they are horde only quests.

This is for the classic wow version

**Comment by PeterMorganGH** [comment]
@GodlFire It looks like this has been fixed already on Git, but was fixed after the last release on Twitch.

**Comment by DFortun81** [comment]
This appears to have been fixed already.
