### ISSUE TITLE
First aid frFR localization (classic)

### ISSUE THREAD

**Issue by LoneWanderer-GH** [DFortun81/ATT-Classic#69]
Hi,

> ATT-Classic Could not find spellID for Secourisme frFR ! Please report this to the ATT Discord!

**Secourisme** corresponds to **First aid.**

| Software | Version |
|-|-|
| World of Wracraft | 1.13.3.32887 |
| ATT-Classic | v0.1.3 |

**Comment by DFortun81** [comment]
Have you had this error occur in the latest version? Our localization detection for spells no longer uses manually entered values.

**Comment by LoneWanderer-GH** [comment]
Yes the error still occurs.

| Software | Version |
|-|-|
| World of Wracraft | 1.13.4.33920 |
| ATT-Classic | v0.1.9 |

**Comment by DFortun81** [comment]
This appears to have been fixed at some point. Please let me know if that is incorrect.
