### ISSUE TITLE
Pets' lower skill ranks

### ISSUE THREAD

**Issue by adrianostanley** [DFortun81/ATT-Classic#80]
I believe the warlock's pet's lower skill ranks should be automatically completed when their higher ranks are achieved because you can't even use a lower rank book if you already bought and used a higher one.

![pets](https://user-images.githubusercontent.com/4955242/81874281-f1d03600-9553-11ea-9f83-f32b69ef3e1c.jpg)

**Comment by DFortun81** [comment]
This issue was fixed once I leveled my Warlock to 60. Please let me know if this is still an issue in Classic Era.
