### ISSUE TITLE
Reset list of known recipes

### ISSUE THREAD

**Issue by shinybeard** [DFortun81/ATT-Classic#81]
I recently unlearned dragonscale leatherworking in favor of tribal leatherworking.
I observed that when I unlearned and re-learned leatherworking - ATT still knows about all my previously learned recipes.
Is there a way to refresh, delete or sync my recipes so that only the actual known recipes are marked as known?

**Comment by DFortun81** [comment]
A common issue with ATT-Classic is that Goblin/Gnomish get stuck, if something like that happens, you can use this command to wipe your current character's cached skills:
`/script wipe(ATTC.CurrentCharacter.Spells); wipe(ATTC.CurrentCharacter.ActiveSkills);
`and then simply reload your UI (/rl)
