### ISSUE TITLE
Quest: Starfall

### ISSUE THREAD

**Issue by Zweshi** [DFortun81/ATT-Classic#85]
The quest called "Starfall" is a optional quest that remains logged as not completed in ATT if you choose to do "To Winterspring!" instead which moves you along to the next quest in the same quest chain and makes "Starfall" unavailable for completion.

Here is the wowhead link for the quest chain:
https://classic.wowhead.com/quest=5249/to-winterspring

**Comment by Chanizu** [comment]
This issue seems to have been fixed already.
