### ISSUE TITLE
Quest: Creature of the Void [Orgrimmar]

### ISSUE THREAD

**Issue by SvenskNavi** [DFortun81/ATT-Classic#88]
The Warlock quest Creature of the Void in Orgrimmar remains listed as a missing quest even though it becomes unobtainable after completing the Undercity variant.

Undercity link: https://classic.wowhead.com/quest=1473/creature-of-the-void
Orgrimmar link: https://classic.wowhead.com/quest=1501/creature-of-the-void

**Comment by SvenskNavi** [comment]
Created a new character just to confirm some specifics. It looks like accepting 1473 doesn't lock you out of 1501, but completion of 1473 does.

**Comment by Chanizu** [comment]
This seems to have been fixed on 27th of November
