### ISSUE TITLE
ATT Classic my feedback

### ISSUE THREAD

**Issue by Kispilka89** [DFortun81/ATT-Classic#89]
Great Addon i love it!

Strange things for me (maybe bug) : 

      Durotar, Quests, Your Place In The World
      Races: Horde only - false
             Avaiable Races: Orc, Troll, Tauren
             Not Avaiable Races: Undead

      Felwood, Quests, Salve via Disenchanting
              Doesn't count when you complete (repeatable)

      Desolace, Quests, -Magram- or -Gelkis- Quests
               You can do only 1 from the 2 quest chains
               Should be all quests removed from the list when you complete the last part 
               of any chain you choosed. (just an idea, would be nice)

      Stranglethorn Vale, Quests, Quest 4621*
                You must be Friendly with Bloodsail Buccaneers to get it.
                Some information says it is not possible anymore if they hate you too much 
                already. The reputation will stop before you reach Friendly with them.
                So it will be impossible to do anymore.
                Should be removed from the list when you reach Hated raputation with 
                Bloodsail Buccaneers.

Thats all what i found non handy for me.
I hope it helps!

The best overall improvement would be an option to remove something from the list by me. These things could be reset if i make a mistake.
This option would solve all future "problems" aswell.

Thanks!
Sorry for my poor english!

**Comment by SvenskNavi** [comment]
Regarding the Kolkar / Gelkis chains, you can do both chains - you just have to go at war and grind reputation for the other clan in order to start the other one.

**Comment by Chanizu** [comment]
"Your Place In The World" is available to undead, but it is a breadcrumb unavailable once you've completed "Cutting Teeth"

The quest IDs for the ""Salve via Disenchanting" were mixed up, this is now fixed on github version.

You can complete both Gelkis/Magram quest chains by killing the other clan until you've reached high enough reputation.

You can increase your bloodsail rep and complete the quests by killing Booty bay guards.
