### ISSUE TITLE
ATT-Classic: Bloodsail Buccaneers reputation not correctly updating?

### ISSUE THREAD

**Issue by Tauril** [DFortun81/ATT-Classic#95]
Hi, I am currently revered at bloodsail buccaneers but ATT still doesn't seem to validate the category for it, is it a known issue?
![bb_rep](https://user-images.githubusercontent.com/8833976/101266530-631d4380-3747-11eb-8f44-d656f517762d.png)

**Comment by Chanizu** [comment]
It is possible to get exalted with the bloodsail buccaneers by doing the quests after reaching 20999/21000

**Comment by Tauril** [comment]
I know, I just didn't think this would be the criterion to validate it. I stopped on purpose at max revered to have a full bar instead of being exalted with half the bar. Unfortunate

**Comment by Chanizu** [comment]
You can "fix" it in Wotlk with https://wow.gamepedia.com/High_Admiral_%22Shelly%22_Jorrik

**Comment by Tauril** [comment]
Yep (if we ever get classic wetly), that's also why I stopped at revered
