### ISSUE TITLE
ATT-Classic - Warlock Grimoires showing 'Not Collected'

### ISSUE THREAD

**Issue by alphabitnz** [DFortun81/ATT-Classic#96]
These Grimoires are all showing 'Not Collected' even though:
a) I have the max ranks learned and you then can't learn lower ranks
b) I learned the lower ranks as I levelled up anyway

And yes this stays the case even when I have the respective pet summoned and refresh the collection database

![image](https://user-images.githubusercontent.com/9102111/102174207-c191b100-3f01-11eb-90f1-374bcf6bfc6a.png)

**Comment by DFortun81** [comment]
I may have just fixed this issue on Git. If you could, please retest using the latest commit.

**Comment by Mosik** [comment]
I can cinfirm that its working now with the latest build

**Comment by ceferrari** [comment]
@DFortun81 
I updated to version 0.4.3, but it is still not working for me. Do I need to do something else to make it work?

**Comment by Mosik** [comment]
> @DFortun81 
> I updated to version 0.4.3, but it is still not working for me. Do I need to do something else to make it work?

So you got the latest git version installed? You have to summon every pet and refresh your collection.

**Comment by ceferrari** [comment]
@Mosik it worked now, when I summoned each pet and refreshed the collection. Thank you

**Comment by alphabitnz** [comment]
can also confirm this is fixed now - just had to summon pet and refresh as others said. thanks!
