### ISSUE TITLE
Glacial set tailoring quest

### ISSUE THREAD

**Issue by oslobar** [DFortun81/ATT-Classic#97]
These quests are not obtainable when you are a tailor
![Capture](https://user-images.githubusercontent.com/4305716/103505838-8a0c8980-4e5b-11eb-90b7-93a279fb2fef.PNG)

**Comment by DFortun81** [comment]
This was fixed a while ago. Blizzard also fixed the ability for Tailors to pick up the handbook from Omarion, so it was actually possible to complete these quests.
